### ISSUE TITLE
Snapchat Stories

### ISSUE THREAD

**Issue by argentdeux** [Nosskirneh/TextEmojis-Public#3]
When the tweak is installed, other people’s Snapchat stories are unable to be loaded (Snapchat v10.18.1) even when Snapchat is blacklisted in settings.

**Comment by Nosskirneh** [comment]
Thanks for reporting.

What version of Snapchat do you use?

**Comment by argentdeux** [comment]
Snapchat v10.18.1
It’s an old version but it is used by a number of people as it has the old UI, has no DRM so can be used with SC++/Scothman and does not give the “unable to refresh” error.
Cheers

**Comment by Nosskirneh** [comment]
My old 6 has v10.19.5 and Snapchat won't let me log in:

> Oh no! You're trying to access Snapchat through a third-party app! Please use the official Snapchat app instead. 👻 

And with v10.18.1:
> You're using a version of Snapchat or operating system no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!

Any ideas? Did you never upgrade and that's why it's working for you?

**Comment by argentdeux** [comment]
I signed in on the latest version and then used “Apps Manager” from BigBoss to backup the app data, then restored it after I’d downloaded the earlier version, that let me get past the error.
I’ve definitely been on the latest and “greatest” version on this account though, I only downgraded when Electra came out heh.
Cheers!

Edit: It’ll crash after a few seconds after opening after doing this, you’ll just need to delete the scheduledlenses file from the Documents folder in Snapchat’s app folder.

**Comment by Nosskirneh** [comment]
Alright, thanks for the detailed description; I managed to get in. Viewing a Snapchat story on v10.18.1 crashes for me even in Safe Mode when nothing tweak related is loaded.

**Comment by argentdeux** [comment]
Sorry to be a pain in the ass, would you mind trying on a brand new Snapchat account to rule out any kind of server sided check? I can definitely view stories, jailbroken or jailed, as long as your tweak isn’t installed. I don’t get any kind of crash. When your tweak is installed and I press on a story it stays pressed/selected and won’t let me do anything else. Without it, everything works fine.

Cheers :)

**Comment by Nosskirneh** [comment]
Haha, you're not a pain in the ass. Suggestions are always welcome. Anyway, I made a new account on the latest version and downgraded back down again, and watching Team Snapchat's stories is working perfectly fine with TextEmojis enabled.

If you create a new account, just for testing, does it magically work for you then?

**Comment by argentdeux** [comment]
Hi Andreas,

Strangely since the last update it just seems to work? I didn’t need to try any other accounts, all seems fine now.

**Comment by Nosskirneh** [comment]
That’s what I suspected. Loading the ad framework seems to have had issues
with several apps. Spotify was an easy fix; it was displaying a black
window above everything. Netflix wouldn’t load at all. And the old Snapchat
app stopped displaying stories. There are possibly more too. Anyway, I’m
glad the issue is resolved.
