### ISSUE TITLE
Apps began crashing 

### ISSUE THREAD

**Issue by kimgc** [Nosskirneh/TextEmojis-Public#5]
Immediately after installing TextEmojis, my apps began crashing (refusing to open). Safari, Google, Reddit, for example. I uninstalled TextEmojis and was able to open them again. I’m having trouble attaching a tweak list here but I can send you one if helpful.

**Comment by Nosskirneh** [comment]
It sounds like the fix I implemented to solve the issue where A12 devices wouldn’t work in sandboxed apps doesn’t work too well on your device.

What version of RocketBootstrap do you have? iOS version and device model? Also, a tweak list would be great!

If you have a crash log, please send me that too.

**Comment by EmptyVisual** [comment]
Hey mate, I’m getting the exact same symptoms, all of my apps are immediately crashing. Uninstalling the tweak fixes the issue.

iPhone XS Max - iOS 12.1
RocketBootstrap 1.0.7~beta5-coolstar-1

Tweak list https://pastebin.com/QbzBqQwd

**Comment by Nosskirneh** [comment]
Thanks for the feedback!

I will look into this as soon as I get the chance to. In the mean time you can downgrade to beta1, it won't work in sandboxed apps on A12 devices, but at least it won't crash.

**Comment by Nosskirneh** [comment]
Fixed in beta3.
