### ISSUE TITLE
Unable to edit homescreen layout

### ISSUE THREAD

**Issue by Kyouda1** [Nosskirneh/TextEmojis-Public#7]
1.3~betas 2-4 break my ability to edit icon layout on homescreen. But 1.3~beta 1 I can.

**Comment by john-crane-69** [comment]
if the issue is fixed then close the ticket

**Comment by Kyouda1** [comment]
Was never fixed

**Comment by Nosskirneh** [comment]
I’ve heard of users having this issue for a long time but I’ve never been able to reproduce it. If your disable TextEmojis in SpringBoard in the latest version, does the issue go away?

**Comment by Kyouda1** [comment]
Well reinstalled it just now and the problem doesn’t seem to happen anymore with 13.5 unc0ver so I guess it can be swept under the rug as is.


Sent from Somewhere on 3rd Density Earth


On Tuesday, May 26, 2020, 17:15, Andreas Henriksson <notifications@github.com> wrote:




I’ve heard of users having this issue for a long time but I’ve never been able to reproduce it. If your disable TextEmojis in SpringBoard in the latest version, does the issue go away?

**Comment by Nosskirneh** [comment]
Very weird. Feel free to reopen this if it starts appearing again!
