### ISSUE TITLE
TextEmoji causes apps to crash when using Text replacement

### ISSUE THREAD

**Issue by john-crane-69** [Nosskirneh/TextEmojis-Public#8]
Hello Andreas
i got textemoji and it’s great, however there is a huge bug there that causes apps to crash

So here is what happens, i use text replacement to like type @@ and it shows my email, now when textemoji is enabled and i type in any text replacement shortcut it crashes that app, i’m sure you can fix it in no time

**Comment by Nosskirneh** [comment]
Hello! Thanks for reporting! Do you get a crash report? I have mine email bound on @mail and it doesn’t seem to happen for me. Maybe you have a special character in your address? I’d love to solve it through!

**Comment by john-crane-69** [comment]
idk why but after disabling all tweaks but text emoji and enabling all of them up again the problem was solved
maybe the device didn’t respring well the first time so i’m sorry i bothered you
consider it closed

**Comment by Nosskirneh** [comment]
Alright, that's weird. No worries though! Feel free to open new issues if you discover anything odd :)

**Comment by john-crane-69** [comment]
hi, i know that i closed the issue but it appeared again and i know how to invoke it everytime
i tried it with all tweaks disabled and the issue still got invoked so you are not going to miss it

there is a website called mock.shop (it’s a gov website to make a curfew appointment rn) 
and on the email cell (which is the third) if you apply the text replacement and press space it crashes the app

**Comment by john-crane-69** [comment]
i tried the new 1.4 beta and it fixed the issue so i’m gonna close this issue

thank you for your hard work man and no rush in releasing 1.4 beta in public
