### ISSUE TITLE
Broken in Apollo

### ISSUE THREAD

**Issue by nloveladyallen** [Nosskirneh/TextEmojis-Public#9]
The emoji selection dialog instantly disappears after typing a colon.

https://imgur.com/a/AJeUGkZ

**Comment by Nosskirneh** [comment]
Thanks for reporting! I’m unable to reproduce it. It seems like as soon as you write a colon, the whole text is selected. Is that due to another tweak? Could you try to disable all other tweaks to eliminate any tweak conflict?

**Comment by nloveladyallen** [comment]
The issue was SearchAutoFocus, which just a few hours ago released an update that fixes it.
